# Generated by Django 5.2.1 on 2025-05-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
